### ISSUE TITLE
Handling complex models using "nuts_numpyro" sampler in HSSM package

### ISSUE THREAD

**Issue by YuanboBQ** [lnccbrown/HSSM#253] opened 2023-08-03 13:38 UTC
Hello,
Thanks for your excellent package. I am currently working with the HSSM package and have encountered an issue while handling my own data, including the "cavanagh_theta" data provided by the package. Specifically, when using more complex models such as hierarchical models with the sampler set to "nuts_numpyro", I am facing the following problem: the sampling process terminates quickly, but the obtained samples are mostly invalid, resulting in very high values for r_hat. I suspect that there might be some issues with the default prior settings.
Could you please investigate this issue and provide some guidance on how to handle more complex models? It would be greatly appreciated if you could also offer a tutorial or example demonstrating the implementation of such complex models.
I am looking forward to your response.
Best regards,
Bo

**Comment by digicosmos86** [comment] 2023-08-03 17:29
Hi Bo,

Thank you for your feedback! Yes, we are working on publishing more tutorials, especially those on creating hierarchical models. In the meantime, if you could share with us your code, we might be able to tell what is happening. Are you using the latest version of HSSM? The latest v0.1.3 version has a lot of stability improvements.

Does this happen when not using the "nuts_numpyro" sampler? One immediate solution might be to switch from the analytical likelihoods to the approximate differentiable likelihoods. The latter is more numerically stable at the moment. Simply add `loglik_kind="approx_differentiable` to the HSSM class definition, and you might see some improvements

**Comment by YuanboBQ** [comment] 2023-08-04 01:57
Hi Paul,
Thanks for your reponse. Yes, I used the latest version of HSSM (v0.1.3). When I test the "cavanagh_theta" data (and my own dataset),  I used the following code
```
# Define a basic hierarchical model with trial-level covariates
hierarchical_ddm_model_reg_v = hssm.HSSM(
    model = "ddm",
    data = cav_data,
    #loglik_kind = "approx_differentiable", 
    include = [
        {
            "name": "v",
            "formula": "v ~ 0 + stim + (1|subj_idx)",
            "link": "identity",
        },
        {
            "name": "z",
            "formula": "z ~ 0 + (1|subj_idx)",
            "link": "identity",
        },     
        {
            "name": "a",
            "formula": "a ~ 0 + (1|subj_idx)",
            "link": "identity",
        },              
    ],     
)
```
or the followling code
```
# Define a basic hierarchical model with trial-level covariates
hierarchical_ddm_model_reg_v = hssm.HSSM(
    model = "ddm",
    data = cav_data,
    #loglik_kind = "approx_differentiable", 
    include = [
        {
            "name": "v",
            "formula": "v ~ 0 + stim + (1|subj_idx)",
            "link": "identity",
        },
        {
            "name": "z",
            "formula": "z ~ 0 + (1|subj_idx)",
            "link": "identity",
        },     
        {
            "name": "a",
            "formula": "a ~ 0 + (1|subj_idx)",
            "link": "identity",
        },
        {
            "name": "t",
            "formula": "t ~ 0 + (1|subj_idx)",
            "link": "identity",
        },                         
    ],     
)
```
the above described issues occured,  both when using default "analytical" or loglik_kind="approx_differentiable. When I used sampler="mcmc", the sampling process was very slow, and there were lot of divergences.

**Comment by igrahek** [comment] 2023-08-04 11:53
I am running into the same issue. I'm working on a dataset with two continuous predictors and a couple of categorical ones, and the model I'm trying to fit worked fine with HDDM. Right now the chains seems to just get completely stuck from the start of the sampling process. I've tried the following:
- Remove priors and use the default ones
- Add p_outlier (and specify the prior on it because the default one is super wide (0-20)
- Increase the default acceptance rate of the sampler

All the chains are still stuck after these changes. I'm adding the latest model code below:

```
# Import the packages
import hssm
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import arviz as az  # Visualization
import pytensor  # Graph-based tensor library
import bambi as bmb


# Setting float precision in pytensor
pytensor.config.floatX = "float32"
pytensor.config.optimizer = 'None'
from jax.config import config
config.update("jax_enable_x64", False)

# Import the data
data = pd.read_csv('../data/data_hddm_LFXC702_EffClean.csv')

# Specify the model
model = hssm.HSSM(
    data=data,
    model = 'ddm',
    loglik_kind="approx_differentiable",
    p_outlier={"name": "TruncatedNormal", "mu":0, "sigma":1,"lower": 0.00001, "upper": 0.5},
    lapse=bmb.Prior("Uniform", lower=0.0, upper=20.0),
    include=[
        {
            "name": "v",
            "prior": {
                "Intercept": {"name": "Uniform", "lower": -3.0, "upper": 3.0},
                "mbased_efficacy_prev": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
		        "mbased_reward_prev": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
            },
            "formula": "v ~ 1 + (1 + mbased_efficacy_prev * mbased_reward_prev + Congruency|subject) + mbased_efficacy_prev * mbased_reward_prev + Congruency",
            "link": "identity",
        },
        {            
            "name": "a",
            "prior": {
                "Intercept": {"name": "Uniform", "lower": 0.01, "upper": 5.0},
                "mbased_efficacy_prev": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
                "mbased_reward_prev": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
            },
            "formula": "a ~ 1 + (1 + mbased_efficacy_prev * mbased_reward_prev|subject) + mbased_efficacy_prev * mbased_reward_prev + scaledRunningTime",
            "link": "identity",
        },
	    {            
            "name": "z",
            "prior": {
                "Intercept": {"name": "Uniform", "lower": 0.0, "upper": 1.0},
                "Congruency": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
            },
            "formula": "z ~ 1  + (1 + Congruency|subject) + Congruency",
            "link": "identity",
        },
    ],
)

# Sample
modelObject = model.sample(
    sampler="nuts_numpyro", 
    chains=4, 
    cores=4, 
    draws=2000, 
    tune=4000,
    target_accept=0.99
)

# Save the model
modelObject.to_netcdf('../output/Model1')


```

**Comment by frankmj** [comment] 2023-08-04 13:59
Hi Bo,

Thanks for helping us sort through this. I just looked at it myself with
the cav_data and got the same thing when using the numpyro version is
running so fast (almost instantaneously for 1000 samples). But then when
using approx_differentiable it ran in a more realistic time (8 minutes for
2 chains, 1000 samples each) and it did converge. You might also try not
specifying the sampler at all and it will default to NUTS.

Others thing you can try:

- make the stim component also hierarchical - currently you are allowing
only overall drift rates to vary by subject but there may be indiv diffs in
the extent to which they are sensitive to stim condition, and forcing them
all to be the same may lead to samplers getting stuck / hard to converge to
account for all the individual data.  I did find this to sample faster and
converge. do this by setting v ~ (stim|subj_idx) + (1|subj_idx)

- set p_outlier to 0 to see if that is interacting with your issues.

**Comment by AlexanderFengler** [comment] 2023-09-05 14:20
Sorry we were out on summer holidays for a bit.
 
We did some work on this, which is reflected already in the main branch and will be part of the next release. 

The main culprit seems to be the `a` parameter here, which is likely initialized to unreasonable values as per bambi defaults (bambi can't know about this). One thing to try is to simply use a log link (forward is exponential) which should bring `a` into reasonable range.

That might resolve the sampler issues right away.

Similarly you can use a logit link on `z`.

Generally we will have to do a bit more work on smart chain initialization, since PyMC / Bambi defaults are somewhat problematic for arbitrary regression models (as per defaults, all the regression betas are initialized via samples from their prior distributions, which can easily bring the regression output, which is our actual parameter of interest, out of range). 

Best,
Alex

**Comment by YuanboBQ** [comment] 2023-09-06 00:00
Hi Alex,

Thanks for your reply. I have test your suggestion. I used the following code:

```
model_reg_vazt = hssm.HSSM(
    data = study1_RTdata,
    hierarchical = False,  ##
    model = 'ddm',
    #loglik_kind = "approx_differentiable",      
    include=[
        {
            "name": "v",                
            "formula": "v ~ 0 + block_name",
            "link": "identity",
        },
       {
            "name": "a",                
            "formula": "a ~ 0 + block_name",
            "link": "log",
        },                     
        {
            "name": "z",                
            "formula": "z ~ 0 + block_name",
            "link": "logit",
        },
        {
            "name": "t",                                
            "formula": "t ~ 0 + block_name",
            "link": "identity",
        },                       
        
    ],
)
```
And I found that the sampling process of one chian terminates quickly, but the sampling process of the other chian was very slow, and the  r_hat values was very high. Is there something worng with the code?

**Comment by digicosmos86** [comment] 2024-05-08 13:20
Closing this for now. In HSSM 0.2.0, we added safe priors and log-logit link functions to tackle convergence issues. Please feel free to try it out and reopen this issue if problem is not solved.

**Closed by digicosmos86** 2024-05-08 13:20 UTC
