### ISSUE TITLE
Example takes forever to run

### ISSUE THREAD

**Issue by DominiqueMakowski** [lnccbrown/HSSM#204] opened 2023-07-13 10:32 UTC
Hiya, after installing a [fresh](#201) python and most (?) dependencies, the example models seem to sample, but takes forever (i.e., its been 1 hour and in the docs it says that it took like 8 seconds I think):

```python
import hssm

# Set float type to float32 to avoid a current bug in PyMC
# This will not be necessary in the future
hssm.set_floatX("float32")

# Load a package-supplied dataset
cav_data = hssm.load_data("cavanagh_theta")

# Define a basic hierarchical model with trial-level covariates
model = hssm.HSSM(
    model="ddm",
    data=cav_data.iloc[1:2000, :],
    include=[
        {
            "name": "v",
            "prior": {
                "Intercept": {"name": "Uniform", "lower": -3.0, "upper": 3.0},
                "theta": {"name": "Uniform", "lower": -1.0, "upper": 1.0},
            },
            "formula": "v ~ (1|subj_idx) + theta",
            "link": "identity",
        },
    ],
)

# Sample from the posterior for this model
model.sample()
```

Here the output it prints before starting to sample (also note that there is no progress bar displayed after the last line, not sure if that's normal):

```
WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Downloading ddm.onnx: 100%
85.1k/85.1k [00:00<00:00, 534kB/s]
[c:\Users\domma\AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py:133](file:///C:/Users/domma/AppData/Local/Programs/Python/Python311/Lib/site-packages/huggingface_hub/file_download.py:133): UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in [C:\Users\domma\.cache\huggingface\hub.](file:///C:/Users/domma/.cache/huggingface/hub.) Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Auto-assigning NUTS sampler...
INFO:pymc.sampling.mcmc:Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
INFO:pymc.sampling.mcmc:Initializing NUTS using jitter+adapt_diag...
WARNING:jax._src.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Multiprocess sampling (4 chains in 4 jobs)
INFO:pymc.sampling.mcmc:Multiprocess sampling (4 chains in 4 jobs)
NUTS: [a, z, t, v_Intercept, v_theta, v_1|subj_idx_sigma, v_1|subj_idx_offset]
INFO:pymc.sampling.mcmc:NUTS: [a, z, t, v_Intercept, v_theta, v_1|subj_idx_sigma, v_1|subj_idx_offset]
```

I suspect that I might be missing some critical dependencies or something like that. Could you let me know if something obvious is causing the slow sampling (maybe it's expected 🤷)? thanks for any pointers!

**Comment by AlexanderFengler** [comment] 2023-07-13 11:18
Hey Dominique,

it seems like the problem is that you don't have g++ installed so the model doesn't actually compile. 
Without the compile step, you are running everything in pure python which will be a lot slower (not surprised to see 2 orders of magnitude or more).

If you are using conda, probably use the provided suggestion `conda install m2w64-toolchain` (in your environment) first. 

What type of machine are you running this on?

**Comment by DominiqueMakowski** [comment] 2023-07-17 14:35
I managed to install g++, and it stopped messaging about that. But unfortunately the sampling still takes some time (didn't reach the end yet), and I'm not if that's normal (and there's no progress bar so it's hard to gauge)

![image](https://github.com/lnccbrown/HSSM/assets/8875533/bf61c0ff-5cab-47ef-87db-97db24b69fae)

Any thoughts?

**Comment by digicosmos86** [comment] 2023-07-18 14:15
There is the warning that PyTensor is using NumPy C-API based implementation for BLAS functions. This can happen for many reasons, but not knowing more about your platform, it's hard to say why. Here's a few things that might help:

1. Reinstall HSSM in your virtual environment. Now that you have `g++` installed, this might make a difference.
2. Where are you running this code? Sometimes VSCode might cause this problem. Some have reported that switching to Jupyter helped resolve this issue.

Hope this helps. If you could let us know a bit more about the platform, your virtual environment, and your Python version, etc, we might be able to provide more tips.

**Comment by AlexanderFengler** [comment] 2023-07-25 14:44
Will close this for now. Doesn't seem like something to fix on the HSSM end?

**Closed by AlexanderFengler** 2023-07-25 14:44 UTC
