### ISSUE TITLE
Translate Basic Tutorial in HDDM to HSSM 

### ISSUE THREAD

**Issue by AisOmar** [lnccbrown/HSSM#125] opened 2023-06-26 15:24 UTC
https://github.com/hddm-devs/hddm/blob/master/hddm/examples/tutorial_basic_hddm.ipynb

**Comment by digicosmos86** [comment] 2023-07-24 22:05
This is a duplicate of #109. Closing this for now

**Closed by digicosmos86** 2023-07-24 22:05 UTC
